server:
  port: 9092
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-recomendation
      database: fitness-recomendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: fitness.exchange
    queue:
      name: activity.queue
    routing:
      key: activity.tracking

  cloud:
    inetutils:
      preferred-networks:
        - "127\\."         # FORCE local network
      ignored-interfaces:
        - "docker.*"
        - "vEthernet.*"
        - "VirtualBox.*"
        - "WSL.*"
      default-ip-address: 127.0.0.1
      default-hostname: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: ai-service:${server.port}:${random.uuid}
    nonSecurePortEnabled: true
    nonSecurePort: 9092

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}